blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView
from .api import PostDetailApiView, PostListApiView


app_name = 'blog'

urlpatterns = []

 
# API URLs
urlpatterns += [
    # Show all posts
    path("api/posts/", PostListApiView.as_view(), name="posts"),
    # Show one post
    path("api/posts/<slug:slug>", PostDetailApiView.as_view(),
         name="single-post"),
    # path('', PostsApiViews.as_view()),
]
# Old template views
urlpatterns += [
    path('', BlogListView.as_view(), name='blog_list'),
    path('posts/<detail_post_slug>',
         BlogDetailView.as_view(), name='post_detail'),
]

home/urls.py
from django.urls import path
from .views import HomeView, redirectHome

app_name = 'home'

urlpatterns = [
    path('', redirectHome),
    path('home', HomeView.as_view(), name="home"),
]

joinnewsletter/urls.py
from django.urls import path
from . import views

app_name = 'joinnewsletter'

urlpatterns = [
    path('', views.newsletter, name='joinnewsletter'),
]

podcaster/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from home.views import redirectHome
from django.views.generic import TemplateView
from django.views.decorators.cache import never_cache
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Blog API')

# Not translated urls
urlpatterns = [
    path('admin/', admin.site.urls),
]

# Internationalised e.g. /en-US/
urlpatterns += i18n_patterns(
    path('blog/', include("blog.urls", namespace='blog')),
    path('podcasts/', include("episodes.urls", namespace='episodes')),
    # This namespace corresponds to save method for slug in models
    path('about', include("about.urls", namespace='about')),
    path('joinnewsletter/', include(
        'joinnewsletter.urls', namespace='joinnewsletter')),
    path('summernote/', include('django_summernote.urls')),
    path('docs', schema_view),
)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# Adding main URL for FrontEnd app
urlpatterns += [re_path('.*',
                        never_cache(TemplateView.as_view(template_name="index.html")))]

admin.site.site_header = "Podcaster Admin"
admin.site.site_title = "Podcaster Admin Portal"
admin.site.index_title = "Welcome to Podcaster Portal"

podcasts/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from home.views import redirectHome
from django.views.generic import TemplateView
from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('blog/', include("blog.urls", namespace='blog')),
    path('podcasts/', include("episodes.urls", namespace='episodes')),
    # This namespace corresponds to save method for slug in models
    path('about', include("about.urls", namespace='about')),
    path('joinnewsletter/', include(
        'joinnewsletter.urls', namespace='joinnewsletter')),
    path('summernote/', include('django_summernote.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# Adding main URL for FrontEnd app
urlpatterns += [re_path('.*',
                        never_cache(TemplateView.as_view(template_name="index.html")))]

admin.site.site_header = "Podcasts Admin"
admin.site.site_title = "Podcasts Admin Portal"
admin.site.index_title = "Welcome to Podcasts Portal"

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.utils.translation import activate
from django.shortcuts import render
from episodes.models import Episode, Category, Tags
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, ListView, View

class HomeView(ListView):
    model = Episode
    # Changning the objects to Episodes that are published
    template_name='home/home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['episodes_list'] = Episode.objects.filter(status='published')[0:3]
        context['last_episode'] = Episode.objects.filter(status='published').first()
        return context

def home(request):
    activate('en')
    episode_list = Episode.objects.filter(status='published')[0:3]
    last_episode = Episode.objects.filter(status='published').first()
    context = {"episodes_list" : episode_list, 
    "last_episode": last_episode}
    print(context)
    return render(request, 'base.html', context)

def redirectHome(request):
    return HttpResponseRedirect('/home')

templates/base.html
{% load static %}
{% load i18n %}
{% load l10n %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <title>{% for el in page_description %}{% if el.name == 'title' %}{{el.content}}{% endif %}{% endfor %}</title>
        <meta charset="utf-8">  
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
        <link rel="icon"          type="image/x-icon" href="{% static 'icons/favicon.ico' %}" >
        <link rel="stylesheet"    type="text/css" href="{% static 'styles/bootstrap-4.1.2/bootstrap.min.css' %}"  >
        <link rel="stylesheet"    type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}" >
        <link rel="stylesheet"    type="text/css" href="{% static 'styles/main_styles.css' %}"  >
        <link rel="stylesheet"    type="text/css" href="{% static 'styles/responsive.css' %}"  >
        {% block css %}
        {% endblock css %}
        <!-- TODO: Implement block of tags  -->

        <!-- //TODO: Implement Twitter og tags into settings -->
        <!-- <meta name="twitter:card" content="TWITTER_IMAGE_URL">
        <meta name="twitter:site" content="@TWITTER_SITE">
        <meta name="twitter:title" content="TWITTER_TITLE">
        <meta name="twitter:description" content="{% for el in page_description %}{% if el.name == 'description' %}{{el.description}}{% endif %}{% endfor %}">
        <meta name="twitter:creator" content="@TWITTER_USERNAME">
        <meta name="twitter:image" content="TWITTER_IMAGE_URL"> -->
        <meta name="twitter:domain" content="{% for el in page_description %}{% if el.name == 'website_url' %}{{el.website_url}}{% endif %}{% endfor %}">
    </head>

    <body>
    <!-- SuperContainer Beginner-->
    <div class="super_container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block home %}
    {% endblock home %}
    {% block blog %}
    {% endblock blog %}
    {% block post_details %}
    {% endblock post_details %}
    {% block about %}
    {% endblock about %}
    {% block episodes %}
    {% endblock episodes %}
    {% block episode_details %}
    {% endblock episode_details %}
    {% include 'footer.html' %}
    <!-- SuperContainer End-->
    </div>
    <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0&appId=1779294385457652&autoLogAppEvents=1"></script>
        <!-- Audioplayer settings -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>       
        <script src="{% static 'styles/bootstrap-4.1.2/popper.js' %}"></script>
        <script src="{% static 'styles/bootstrap-4.1.2/bootstrap.min.js' %}"></script>
        <script src="{% static 'plugins/parallax.min.js' %}"></script>
        <script src="{% static 'plugins/scrollmagic.min.js' %}"></script>

        {% block js %}
        {% endblock js %}
        <script src="{% static 'js/custom.js' %}"></script>

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=GOOGLE_ANALYTICS_NUMBER"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'GOOGLE_ANALYTICS_NUMBER');
        </script>

    </body>

</html>

templates/biweekly.html
	<!-- Bi Weekly -->

	<div class="weekly">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="" data-speed="0.8"></div>
		<div class="container">
			<div class="row row-eq-height">
				
				<!-- Weekly Content -->
				<div class="col-lg-6">
					<div class="weekly_content d-flex flex-column align-items-start justify-content-lg-center justify-content-start">
						<div>
							<div class="weekly_title"><h1>Bi-weekly episodes</h1></div>
							<div class="weekly_text">
								<p>Cras congue et risus eget congue. Integer id justo non orci suscipit cursus a scelerisque libero. Fusce in tortor mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas euismod sed magna.</p>
							</div>
							<div class="shops d-flex flex-row align-items-start justify-content-start flex-wrap">
								<div class="button_border"><a href="#">Amazon</a></div>
								<div class="button_border"><a href="#">Itunes</a></div>
								<div class="button_border"><a href="#">Spotify</a></div>
							</div>
						</div>
					</div>
				</div>

				<!-- Weekly Image -->
				<div class="col-lg-6">
					<div class="weekly_image">
						<img src="" alt="">
						<div class="logo">
							<a href="#" class="d-flex flex-row"><span>my</span>podcast<div><img src="" alt=""></div></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

templates/footer.html
{% load static %}
{% load i18n %}
{% load l10n %}


<!-- Newsletter -->

<div class="newsletter text-white">
	<div class="parallax_background parallax-window" data-parallax="scroll"
		data-image-src="" data-speed="0.8"></div>
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="section_title text-white text-center">
					<h1>{% trans "Join my Newsletter" %}</h1>
				</div>
				<div class="newsletter_text text-center">
					<p>{% trans "Get latest posts, podcasts and giveaways informations." %}</p>
				</div>
			</div>
		</div>
		<div class="row newsletter_row">
			<div class="col-lg-10 offset-lg-1">
				<div class="newsletter_form_container">
					<form enctype="multipart/form-data" method="POST" action="{% url 'joinnewsletter:joinnewsletter' %}"
						class="newsletter_form d-flex flex-md-row flex-column align-items-md-start align-items-center justify-content-md-between justify-content-start"
						id="newsletter_form">
						{% csrf_token %}
						<input id="id_email_field" name="email" type="email"
						placeholder="Email" aria-label="email" class="form-control newsletter_input" required="required">
						<button class="btn btn-primary newsletter_button button_fill" id="id_submit_home" name="submit" value="Subscribe"
						type="submit">{% trans "subscribe" %}!</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
	<!-- Footer -->

	<footer class="footer">
		<div class="container">
			<div class="row footer_logo_row">
				<div class="col d-flex flex-row align-items-center justify-content-center">
					<div class="logo">
						<a href="/">{% for el in page_description %}{% if el.name == 'title' %}{{el.content}}{% endif %}{% endfor %}</a>
					</div>
				</div>
			</div>
			<div class="row footer_content_row">

				<!-- Latest Podcasts -->
				<div class="col-lg-3">
					<div class="footer_title">{% trans "Latest Podcasts" %}</div>
					<div class="latest_container">
						{% for episode in latest_episodes %}
						<!-- Latest -->
						<div class="latest">
							<div class="latest_title_container d-flex flex-row align-items-start justify-content-start">
								<a href="episode.html">
									<div class="d-flex flex-row align-items-start justify-content-start">
										<div class="latest_play">
											<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="512px" height="512px" viewBox="0 0 714 714" style="enable-background:new 0 0 714 714;" xml:space="preserve">
												<g id="Play">
													<path d="M641.045,318.521L102,0C73.822,0,51,22.822,51,51v612c0,28.178,22.822,51,51,51l539.045-318.521      C654.661,387.422,663,372.81,663,357C663,341.19,654.661,326.579,641.045,318.521z M153,565.386V148.614L505.665,357      L153,565.386z" fill="#FFFFFF"/>
												</g>
											</svg>
										</div>
										<div class="latest_title_content">
											<div class="latest_title">{{episode.title}}</div>
										</div>
									</div>
								</a>
							</div>
							<div class="latest_episode_info">
								<ul class="d-flex flex-row align-items-start justify-content-start">
									<li>{{episode.updated}}</li>
								</ul>
							</div>
						</div>
						{% endfor %}


					</div>
				</div>

				<!-- Latest Posts -->
				<div class="col-lg-3">
					<div class="footer_title">{% trans "Latest Posts" %}</div>
					<div class="latest_container">
					{% for post in latest_posts %}
						<!-- Latest -->
						<div class="latest">
							<div class="latest_title_container d-flex flex-row align-items-start justify-content-start">
								<a href="episode.html">
									<div class="d-flex flex-row align-items-start justify-content-start">
										<div class="latest_play">
											<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="512px" height="512px" viewBox="0 0 714 714" style="enable-background:new 0 0 714 714;" xml:space="preserve">
												<g id="Play">
													<path d="M641.045,318.521L102,0C73.822,0,51,22.822,51,51v612c0,28.178,22.822,51,51,51l539.045-318.521      C654.661,387.422,663,372.81,663,357C663,341.19,654.661,326.579,641.045,318.521z M153,565.386V148.614L505.665,357      L153,565.386z" fill="#FFFFFF"/>
												</g>
											</svg>
										</div>
										<div class="latest_title_content">
											<div class="latest_title">{{ post.title }}</div>
										</div>
									</div>
								</a>
							</div>
							<div class="latest_episode_info">
								<ul class="d-flex flex-row align-items-start justify-content-start">
									<li>{{ post.publish }}</li>
								</ul>
							</div>
						</div>
							{% comment %} {% for episode in latest_posts %}{% endfor %} {% endcomment %}
						{% endfor %} 
					</div>
				</div>
				<!-- Tags -->
				<div class="col-lg-3">
					<div class="footer_title">{% trans "Tags" %}</div>
					<div class="footer_list">
						{% for tag in tags %}
						<div><div><a href="#">{{tag.title}}</a></div></div>
						{% endfor %}
					</div>
				</div>
				<!-- categories -->
				<div class="col-lg-3">
					<div class="footer_title">{% trans "Categories" %}</div>
					<div class="footer_list">
						{% for category in categories %}
						<div><div><a href="#">{{category.title}}</a></div></div>
						{% endfor %}
					</div>
				</div>
				{% comment %} <!-- Gallery -->
				<div class="col-lg-3">
					<div class="footer_title">Instagram</div>
					<div class="gallery d-flex flex-row align-items-start justify-content-start flex-wrap">
						
						<!-- Gallery Item -->
						<div class="gallery_item">
							<a class="colorbox" ><img src="" alt=""></a>
						</div>
					</div>
				</div>  {% endcomment %}
			</div>
			<div class="row footer_social_row">
				<div class="col">
					<div class="footer_social">
						<ul class="d-flex flex-row align-items-center justify-content-center">
						{% for el in social_media %}
							<li><a href="{{el.link}}"><i class="fa fa-{{el.name}}" aria-hidden="true"></i></a></li>
						{% endfor %}
						</ul>
					</div>
				</div>
			</div>

</br></br><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
This page is openSource <i class="fa fa-heart-o" aria-hidden="true"></i>  and available on GitHub by <a href="https://github.com/hvitis" target="_blank">Hvitis</a> | Template made by Colorlib
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

		</div>
	</footer>

templates/header.html
{% load static %}
{% load i18n %}
{% load l10n %}
	<!-- Header -->

	<header class="header trans_400">

		<!-- Logo -->
		<div class="logo">
			<a href="/">{% for el in page_description %}{% if el.name == 'title' %}{{el.content}}{% endif %}{% endfor %} </i></a>
			
		</div>

		<div class="container">
			{% if messages %}
			<ul class="messages">
				{% for message in messages %}
				<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
				<div class="alert alert-success" role="alert">
			  {{message}}
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			  </button>
			</div>
				</li>
				{% endfor %}
			</ul>
			{% endif %}
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-between trans_400">
						<nav class="main_nav">
							<ul class="d-flex flex-row align-items-end justify-content-end">
								<li><a href="/">Home</a></li>
								<li><a href="/podcasts">{% trans "Podcasts" %}</a></li>
								<li><a href="/blog">{% trans "Blog" %}</a></li>
								<li><a href="/about">{% trans "About" %}</a></li>
							</ul>
						</nav>
						<nav class="main_nav">
							<ul class="d-flex flex-row align-items-end justify-content-end">
								<li><a class="lang_icon" href="/en-us/home"><img src="{% static 'icons/en.svg' %}" width="20px" /> {% trans "English" %}</a></li>
								<li><a class="lang_icon" href="/de-de/home"><img src="{% static 'icons/de.svg' %}" width="20px" />  {% trans "German" %}</a></li>
							</ul>
						</nav> 
					</div> 
				</div>
			</div> 
		</div>

		<!-- Submit & Social -->
		<div class="header_right d-flex flex-row align-items-start justify-content-start">

			<!-- Social -->
			<div class="social">
				<ul class="d-flex flex-row align-items-start justify-content-start">
				{% for el in social_media %}
					<li><a href="{{el.link}}"><i class="fa fa-{{el.name}}" aria-hidden="true"></i></a></li>
				{% endfor %}
				</ul> 
			</div>
			
			<!-- Hamburger -->
			<div class="hamburger"><i class="fa fa-bars" aria-hidden="true"></i></div>
			
		</div>
	</header>

templates/home.html
{% load static %}
{% load i18n %}
{% load l10n %}
{% load thumbnail %}
<!-- Home -->

<div class="home">
    <div class="background_image" style="background-image:url({% for el in page_background %}{% if el.name in request.path %}{{el.image.url}}{% endif %}{% endfor %})">
    </div>
    <div class="home_container">

        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="home_content">
                        <div class="tags">
                            <ul class="d-flex flex-row align-items-start justify-content-start">
                                {% for el in last_episode.category.all %}
                                <li><a href="#">{{el.title}}</a></li>
                                {% endfor %}

                            </ul>
                        </div>
                        <div class="home_title">
                            <h1>{{last_episode.title}}</h1>
                        </div>
                        <div class="home_subtitle">{{last_episode.description}}</div>
                        <div class="track_info">
                            <ul class="d-flex flex-row align-items-start justify-content-start">
                                <li><a href="#">{{last_episode.timestamp}}</a></li>
                                {% comment %} <li><a href="#">Music</a></li> {% endcomment %}
                                {% comment %} <li>56:40</li> {% endcomment %}
                                {% comment %} <li><a href="#">0 Comments</a></li> {% endcomment %}
                            </ul>
                        </div>

                        <div class="track track_home">
                            <div class="card p-2" style="background: #ffffff26;">
                                <!-- Player -->
                                <div class="player-background">
                                    <div id="ag1" class="audiogallery">
                                        <div class="items">
                                            <div class="audioplayer-tobe" style="width:100%; " data-thumb="{{last_episode.thumbnail.url}}" data-bgimage="{% static 'audioplayer/img/bg.jpg' %}" data-scrubbg="{% static 'audioplayer/waves/scrubbg.png' %}" data-scrubprog="{% static 'audioplayer/waves/scrubprog.png' %}" data-videoTitle="Audio Video" data-type="normal" data-source="{{last_episode.audio.url}}" data-sourceogg="{{last_episode.audio.url}}">
                                                <div class="meta-artist"><span class="the-artist">{{last_episode.author}}</span><br /><span class="the-name">{{last_episode.author}}
                                                </div>
                                                <div class="menu-description">
                                                    <div class="menu-item-thumb-con">
                                                        <div class="menu-item-thumb" style="background-image: url({{last_episode.thumbnail.url}})">
                                                        </div>
                                                    </div>
                                                    <span class="the-artist">{{last_episode.author}}</span>
                                                    <span class="the-name">{{last_episode.author}}</span>
                                                </div>

                                            </div>

                                        </div>
                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>
                    <div class="button_border home_button trans_200"><a href="#">More Info</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<!-- Shows -->

<div class="shows">
    <div class="container">
        <div class="row shows_row">
            {% for single_episode in episodes_list %}

            <!-- Show -->
            <div class="col-lg-4">
                <div class="show">
                    <div class="show_image">
                        <a href="/episodes">
                            {% thumbnail single_episode.thumbnail "400x300" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                            {% endthumbnail %}
                        </a>
                        <div class="show_tags">
                            <div class="tags">
                                <ul class="d-flex flex-row align-items-start justify-content-start">
                                    {% for category in single_episode.category.all %}
                                    <li><a href="#">{{category.title}}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="show_play_icon"><img src="{% static 'images/play.svg' %}" alt="https://www.flaticon.com/authors/cole-bemis"></div>
                    </div>
                    <div class="show_content">
                        <div class="show_date">{{single_episode.publish}}</div>
                        <div class="show_title"><a href="episode.html">{{single_episode.title}}</a></div>
                        <div class="show_info d-flex flex-row align-items-start justify-content-start">
                            <div class="show_fav d-flex flex-row align-items-center justify-content-start">
                                <a href='{{single_episode.url}}'>
                                    <div class="show_fav_icon show_info_icon"><img class="svg" src="{% static 'images/heart.svg' %}" alt=""></div>
                                </a>
                                <div class="show_fav_count">Share</div>
                            </div>
                            {% comment %} <div class="show_comments">
                                <a href="#">
                                    <div class="d-flex flex-row align-items-center justify-content-start">
                                        <div class="show_comments_icon show_info_icon"><img class="svg" src="{% static 'images/speech-bubble.svg' %}" alt=""></div>
                                        <div class="show_comments_count">88 Comments</div>
                                    </div>
                                </a>
                            </div> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="row">
            <div class="col text-center">
                <div class="button_fill shows_button"><a href="/episodes">browse shows</a></div>
            </div>
        </div>
    </div>
</div>

{% comment %}

<!-- Categories 2 -->

<div class="shows_2">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="shows_2_title">By Category</div>
            </div>
        </div>
        <div class="row shows_2_row">

            <!-- Category -->
            <div class="col-xl-3 col-md-6">
                <div class="show">
                    <div class="show_image">
                        <a href="episode.html">
                            <img src="{% static 'images/show_4.jpg' %}" alt="https://unsplash.com/@h4rd3n">
                            <div class="show_play_icon"><img src="{% static 'images/play.svg' %}" alt="https://www.flaticon.com/authors/cole-bemis"></div>
                            <div class="show_title_2">Cras malesuada ipsum sapien.</div>
                        </a>
                        <div class="show_tags">
                            <div class="tags">
                                <ul class="d-flex flex-row align-items-start justify-content-start">
                                    <li><a href="#">travel</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
        <div class="row">
            <div class="col text-center">
                <div class="button_fill shows_2_button"><a href="#">browse shows</a></div>
            </div>
        </div>
    </div>
</div> {% endcomment %}

templates/navbar.html
	<!-- Menu -->

	<div class="menu">
		<div class="menu_content d-flex flex-column align-items-end justify-content-start">
			<ul class="menu_nav_list text-right">
				<li><a href="/">Home</a></li>
				<li><a href="/podcasts">Podcasts</a></li>
				<li><a href="/blog">Blog</a></li>
				<li><a href="/about">About</a></li>
				{% comment %} <li><a href="contact.html">Contact</a></li> {% endcomment %}
			</ul>
			<div class="menu_extra d-flex flex-column align-items-end justify-content-start">
				{% comment %} <div class="menu_submit"><a href="#">Submit your podcast</a></div> {% endcomment %}
				<div class="social">
					<ul class="d-flex flex-row align-items-start justify-content-start">
						{% for el in social_media %}
							<li><a href="{{el.link}}"><i class="fa fa-{{el.name}}" aria-hidden="true"></i></a></li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</div>

templates/tags_categories.html
{% load static %}
{% load thumbnail %}
{% load i18n %}
{% load l10n %}

<!-- Categories -->
<div class="sidebar_list">
    <div class="sidebar_title">{% trans "Categories" %}</div>
    <ul>
        {% for el in categories %}
        <li><a href="#">{{el.title}}</a></li>
        {% endfor %}
    </ul>
</div>

<!-- Tags -->
<div class="sidebar_tags">
    <div class="sidebar_title">{% trans "Tags" %}</div>
    <div class="tags">
        <ul class="d-flex flex-row align-items-start justify-content-start flex-wrap">
            {% for tag in tags %}
            <li><a href="#">{{tag.title}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>